on: [push]

name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Test
        run: .github/run.sh --lint n

      - name: Lint
        run: .github/run.sh --test n --fix n
