on: [push]

name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Test
        run: |
          shopt -s globstar
          for toml in **/Cargo.toml; do
            cargo test --all-features --manifest-path $toml -- --ignored
          done
      
      - name: Lint
        run: |
          shopt -s globstar
          for toml in **/Cargo.toml; do
            # https://linuxcommandlibrary.com/man/rustfmt
            # https://github.com/rust-lang/rustfmt
            cargo fmt --manifest-path $toml -- --check
            # https://github.com/rust-lang/rust-clippy
            cargo clippy --manifest-path $toml -- -D warnings 
          done 
